package wgsl

import (
	"fmt"
	"strings"
	"tach/foundation"
	"tach/ir"
)

type program struct {
	executable *plan
	source     *ir.KernelModule
	functions  map[*ir.Function]*ir.Coordinates
	kernels    map[*ir.Function]*physicalKernel
}

type Result struct {
	Source       string
	KernelModule *ir.KernelModule
	RuntimeJSON  []byte
}

func Lower(logical *ir.Module) (*Result, error) {
	executable, err := planModule(logical)
	if err != nil {
		return nil, err
	}
	return finish(executable)
}

func finish(executable *plan) (*Result, error) {
	result := &Result{KernelModule: executable.KernelModule}
	var err error
	result.RuntimeJSON, err = encodeRuntime(executable)
	if err != nil {
		return nil, err
	}
	result.Source, err = emit(executable)
	if err != nil {
		return nil, err
	}
	return result, nil
}

func lower(executable *plan) (*program, error) {
	functions := map[*ir.Function]*ir.Coordinates{}
	kernels := map[*ir.Function]*physicalKernel{}
	for index := range executable.PhysicalKernels {
		kernel := &executable.PhysicalKernels[index]
		functions[kernel.Function], kernels[kernel.Function] = kernel.Coordinates, kernel
	}
	functions, err := ir.ResolveFunctionCoordinates(executable.KernelModule, functions)
	if err != nil {
		return nil, err
	}
	return &program{executable: executable, source: executable.KernelModule, functions: functions, kernels: kernels}, nil
}

func needs(f *ir.Coordinates, space ir.CoordinateSpace) bool {
	for id, coordinate := range f.Values {
		if coordinate.Space == space && f.Uses[id] > 0 {
			return true
		}
	}
	return false
}

func expression(f *ir.Coordinates, id ir.ValueID) (string, bool) {
	coordinate, ok := f.Values[id]
	if !ok {
		return "", false
	}
	name, suffix := "_tach_global_index", "."+[]string{"x", "y", "z"}[coordinate.Dimension]
	if coordinate.Space == ir.Local {
		name = "_tach_local_index"
	} else if coordinate.Space == ir.LocalLinear {
		name, suffix = "_tach_local_linear", ""
	}
	return name + suffix, true
}

func mangleFunc(name string) string          { return "_tach_f_" + ir.MangleIdentifier(name) }
func mangleType(name string) string          { return "_tach_t_" + ir.MangleIdentifier(name) }
func resourceName(kernel, buffer int) string { return fmt.Sprintf("_tach_r%d_%d", kernel, buffer) }
func wrapperName(kernel, buffer int) string {
	return fmt.Sprintf("_tach_resource_%d_%d", kernel, buffer)
}
func fieldName(i int, name string) string { return fmt.Sprintf("f%d_%s", i, ir.MangleIdentifier(name)) }
func workgroupName(f *ir.Function, i int) string {
	return fmt.Sprintf("_tach_w_%s_%d", ir.MangleIdentifier(f.Name), i)
}

type emitter struct {
	p           *program
	m           *ir.KernelModule
	b           strings.Builder
	indent      int
	structIndex map[string]int
	funcIndex   map[string]int
	kernelIndex map[*ir.Function]int
}

func emit(executable *plan) (string, error) {
	if err := verify(executable); err != nil {
		return "", err
	}
	p, err := lower(executable)
	if err != nil {
		return "", err
	}
	m := executable.KernelModule
	e := &emitter{p: p, m: m, structIndex: map[string]int{}, funcIndex: map[string]int{}, kernelIndex: map[*ir.Function]int{}}
	for i := range executable.PhysicalKernels {
		e.kernelIndex[executable.PhysicalKernels[i].Function] = i
	}
	for i, t := range m.Structs {
		e.structIndex[t.Name] = i
	}
	for i, f := range m.Functions {
		e.funcIndex[f.Name] = i
	}
	e.line("// Generated by Tach. Portable WGSL compute profile.")
	if ir.UsesKind(m, foundation.Float16Kind) {
		e.line("enable f16;")
	}
	e.line("")
	for _, t := range m.Structs {
		e.emitStruct(t)
		e.line("")
	}
	for kernelIndex, kernel := range executable.PhysicalKernels {
		for bufferIndex, buffer := range kernel.Function.BufferParams {
			if kernel.Bindings[bufferIndex].Texture {
				e.line("@group(0) @binding(%d) var %s: texture_storage_2d<rgba8unorm, write>;", bufferIndex, resourceName(kernelIndex, bufferIndex))
			} else {
				e.emitResource(kernelIndex, bufferIndex, buffer)
			}
			e.line("")
		}
		if kernel.Parameters != nil {
			e.emitParameterBlock(kernel.Parameters)
			e.line("")
		}
	}
	for _, f := range m.Functions {
		if f.Kind == ir.Helper {
			continue
		}
		for i, w := range f.WorkgroupVars {
			e.line("var<workgroup> %s: %s;", workgroupName(f, i), e.typeName(w.Type))
		}
		if len(f.WorkgroupVars) > 0 {
			e.line("")
		}
	}
	for _, f := range m.Functions {
		if f.Kind == ir.Helper {
			if err := e.emitFunction(f); err != nil {
				return "", err
			}
			e.line("")
		}
	}
	for _, f := range m.Functions {
		if f.Kind == ir.Stage {
			if err := e.emitFunction(f); err != nil {
				return "", err
			}
			e.line("")
		}
	}
	out := e.b.String()
	if err := Validate(out); err != nil {
		return "", fmt.Errorf("tach WGSL self-validation failed: %w", err)
	}
	return out, nil
}

func viewTexture(physical *physicalKernel, buffer int) bool {
	return physical != nil && buffer >= 0 && buffer < len(physical.Bindings) && physical.Bindings[buffer].Texture
}

func (e *emitter) line(s string, args ...any) {
	for i := 0; i < e.indent; i++ {
		e.b.WriteString("  ")
	}
	if len(args) > 0 {
		fmt.Fprintf(&e.b, s, args...)
	} else {
		e.b.WriteString(s)
	}
	e.b.WriteByte('\n')
}
func (e *emitter) typeName(t *foundation.Type) string {
	switch t.Kind {
	case foundation.VoidKind:
		return "void"
	case foundation.BoolKind:
		return "bool"
	case foundation.Int32Kind:
		return "i32"
	case foundation.Uint32Kind:
		return "u32"
	case foundation.Float16Kind:
		return "f16"
	case foundation.Float32Kind:
		return "f32"
	case foundation.VectorKind:
		return fmt.Sprintf("vec%d<%s>", t.Lanes, e.typeName(t.Elem))
	case foundation.StructKind:
		return mangleType(t.Name)
	case foundation.AtomicKind:
		return fmt.Sprintf("atomic<%s>", e.typeName(t.Elem))
	case foundation.FixedArrayKind:
		return fmt.Sprintf("array<%s, %d>", e.typeName(t.Elem), t.Count)
	case foundation.RuntimeArrayKind:
		return fmt.Sprintf("array<%s>", e.typeName(t.Elem))
	default:
		return "__invalid"
	}
}
func (e *emitter) emitStruct(t *foundation.Type) {
	e.line("// Tach type: %s", t.Name)
	e.line("struct %s {", mangleType(t.Name))
	e.indent++
	for i, f := range t.Fields {
		prefix := ""
		if i == 0 && !hasRuntimeTail(t) {
			prefix = "@align(16) "
		}
		e.line("%s%s: %s,", prefix, fieldName(i, f.Name), e.typeName(f.Type))
	}
	e.indent--
	e.line("}")
}
func (e *emitter) emitResource(kernel, buffer int, r ir.BufferParam) {
	e.line("// Tach resource: %s", r.Name)
	access := "read"
	if r.Access == ir.Mutable || foundation.ContainsAtomic(r.Type) {
		access = "read_write"
	}
	if r.Type.Kind == foundation.StructKind && hasRuntimeTail(r.Type) {
		e.line("@group(0) @binding(%d) var<storage, %s> %s: %s;", buffer, access, resourceName(kernel, buffer), e.typeName(r.Type))
		return
	}
	w := wrapperName(kernel, buffer)
	e.line("struct %s {", w)
	e.indent++
	fieldType := e.typeName(r.Type)
	if hasRuntimeTail(r.Type) {
		// Runtime array length is derived from the bound byte size. Imposing the
		// fixed-resource 16-byte wrapper alignment here would raise the shader's
		// minimum binding size and turn padding bytes into phantom elements.
		e.line("data: %s,", fieldType)
	} else {
		e.line("@align(16) data: %s,", fieldType)
	}
	e.indent--
	e.line("}")
	e.line("@group(0) @binding(%d) var<storage, %s> %s: %s;", buffer, access, resourceName(kernel, buffer), w)
}

func parameterTypeName(block *ir.HostParameterBlock) string {
	return "_tach_parameters_" + ir.MangleIdentifier(block.Function.Name)
}

func parameterResourceName(block *ir.HostParameterBlock) string {
	return "_tach_p_" + ir.MangleIdentifier(block.Function.Name)
}

func (e *emitter) emitParameterBlock(block *ir.HostParameterBlock) {
	e.line("// Tach parameters: %s", block.Function.Name)
	e.line("struct %s {", parameterTypeName(block))
	e.indent++
	for index, field := range block.Fields {
		prefix := ""
		if index == 0 {
			prefix = "@align(16) "
		}
		e.line("%s%s: %s,", prefix, field.Name, e.typeName(field.Physical))
	}
	e.indent--
	e.line("}")
	e.line("@group(0) @binding(%d) var<uniform> %s: %s;", block.Binding, parameterResourceName(block), parameterTypeName(block))
}

func hasRuntimeTail(t *foundation.Type) bool {
	if t == nil {
		return false
	}
	if t.Kind == foundation.RuntimeArrayKind {
		return true
	}
	return t.Kind == foundation.StructKind && len(t.Fields) > 0 && hasRuntimeTail(t.Fields[len(t.Fields)-1].Type)
}

func (e *emitter) funcName(f *ir.Function) string {
	if f.Kind == ir.Stage {
		return f.Name
	}
	return mangleFunc(f.Name)
}
func (e *emitter) emitFunction(f *ir.Function) error {
	if f.Kind == ir.Stage {
		e.line("// Tach compute entry: %s", f.Name)
		workgroup := e.p.kernels[f].Workgroup
		e.line("@compute @workgroup_size(%d, %d, %d)", workgroup[0], workgroup[1], workgroup[2])
	}
	var params []string
	if f.Kind == ir.Stage {
		lowered := e.p.functions[f]
		if needs(lowered, ir.Global) {
			params = append(params, "@builtin(global_invocation_id) _tach_global_index: vec3<u32>")
		}
		if needs(lowered, ir.Local) {
			params = append(params, "@builtin(local_invocation_id) _tach_local_index: vec3<u32>")
		}
		if needs(lowered, ir.LocalLinear) {
			params = append(params, "@builtin(local_invocation_index) _tach_local_linear: u32")
		}
	} else {
		for _, p := range f.Params {
			params = append(params, fmt.Sprintf("_v%d: %s", p.ID, e.typeName(p.Type)))
		}
	}
	head := fmt.Sprintf("fn %s(%s)", e.funcName(f), strings.Join(params, ", "))
	if f.Return.Kind != foundation.VoidKind {
		head += fmt.Sprintf(" -> %s", e.typeName(f.Return))
	}
	e.line("%s {", head)
	e.indent++
	st := &fnState{e: e, f: f, lowered: e.p.functions[f], values: map[ir.ValueID]*foundation.Type{}, places: map[ir.PlaceID]placeExpr{}}
	for _, id := range st.lowered.Order {
		if st.lowered.Uses[id] == 0 {
			continue
		}
		value, _ := expression(st.lowered, id)
		e.line("let %s: u32 = %s;", v(id), value)
		st.def(id, foundation.Uint32Type)
	}
	for _, p := range f.Params {
		if f.Kind == ir.Helper {
			st.values[p.ID] = p.Type
		}
	}
	if f.Kind == ir.Stage {
		block := e.p.kernels[f].Parameters
		cursor := 0
		for parameter, p := range f.Params {
			expression, err := e.parameterExpression(block, parameter, p.Type, &cursor)
			if err != nil {
				return err
			}
			e.line("let %s: %s = %s;", v(p.ID), e.typeName(p.Type), expression)
			st.def(p.ID, p.Type)
		}
		if block != nil && cursor != len(block.Fields) {
			return fmt.Errorf("kernel %s parameter block consumed %d of %d fields", f.Name, cursor, len(block.Fields))
		}
	}
	if err := st.emitBlock(f.Body, nil); err != nil {
		return err
	}
	e.indent--
	e.line("}")
	return nil
}

func (e *emitter) parameterExpression(block *ir.HostParameterBlock, parameter int, logical *foundation.Type, cursor *int) (string, error) {
	if logical.Kind == foundation.StructKind {
		values := make([]string, len(logical.Fields))
		for index, field := range logical.Fields {
			value, err := e.parameterExpression(block, parameter, field.Type, cursor)
			if err != nil {
				return "", err
			}
			values[index] = value
		}
		return fmt.Sprintf("%s(%s)", e.typeName(logical), strings.Join(values, ", ")), nil
	}
	if block == nil || *cursor >= len(block.Fields) {
		return "", fmt.Errorf("kernel parameter %d has no physical field", parameter)
	}
	field := block.Fields[*cursor]
	*cursor = *cursor + 1
	if field.Parameter != parameter || !foundation.Equal(field.Logical, logical) {
		return "", fmt.Errorf("kernel parameter %d field %d does not match %s", parameter, *cursor-1, logical)
	}
	expression := parameterResourceName(block) + "." + field.Name
	if logical.Kind == foundation.BoolKind {
		expression = "(" + expression + " != 0u)"
	}
	return expression, nil
}
