package wgsl

import (
	"fmt"
	"strings"

	"tach/src/backend"
	"tach/src/foundation"
	"tach/src/ir"
)

type program struct {
	executable *backend.Executable
	source     *ir.KernelModule
	functions  map[*ir.Function]*backend.Coordinates
	kernels    map[*ir.Function]*backend.PhysicalKernel
}

func Lower(logical *ir.Module) (*backend.Executable, error) {
	return backend.Lower(logical, backend.WebProfile)
}

func lower(executable *backend.Executable) (*program, error) {
	functions, kernels, err := executable.IndexFunctions()
	if err != nil {
		return nil, err
	}
	return &program{executable: executable, source: executable.KernelModule, functions: functions, kernels: kernels}, nil
}

func needs(f *backend.Coordinates, space backend.CoordinateSpace) bool {
	for id, coordinate := range f.Values {
		if coordinate.Space == space && f.Uses[id] > 0 {
			return true
		}
	}
	return false
}

func expression(f *backend.Coordinates, id ir.ValueID) (string, bool) {
	coordinate, ok := f.Values[id]
	if !ok {
		return "", false
	}
	name, suffix := "_tach_global_index", "."+[]string{"x", "y", "z"}[coordinate.Dimension]
	if coordinate.Space == backend.Local {
		name = "_tach_local_index"
	} else if coordinate.Space == backend.LocalLinear {
		name, suffix = "_tach_local_linear", ""
	}
	return name + suffix, true
}

func mangleFunc(name string) string          { return "_tach_f_" + ir.MangleIdentifier(name) }
func mangleType(name string) string          { return "_tach_t_" + ir.MangleIdentifier(name) }
func resourceName(kernel, buffer int) string { return fmt.Sprintf("_tach_r%d_%d", kernel, buffer) }
func wrapperName(kernel, buffer int) string {
	return fmt.Sprintf("_tach_resource_%d_%d", kernel, buffer)
}
func fieldName(i int, name string) string { return fmt.Sprintf("f%d_%s", i, ir.MangleIdentifier(name)) }
func workgroupName(f *ir.Function, i int) string {
	return fmt.Sprintf("_tach_w_%s_%d", ir.MangleIdentifier(f.Name), i)
}

type emitter struct {
	p           *program
	m           *ir.KernelModule
	b           strings.Builder
	indent      int
	structIndex map[string]int
	funcIndex   map[string]int
	kernelIndex map[*ir.Function]int
}

func Emit(executable *backend.Executable) (string, error) {
	if err := backend.Verify(executable); err != nil {
		return "", err
	}
	p, err := lower(executable)
	if err != nil {
		return "", err
	}
	m := executable.KernelModule
	e := &emitter{p: p, m: m, structIndex: map[string]int{}, funcIndex: map[string]int{}, kernelIndex: map[*ir.Function]int{}}
	for i := range executable.PhysicalKernels {
		e.kernelIndex[executable.PhysicalKernels[i].Function] = i
	}
	for i, t := range m.Structs {
		e.structIndex[t.Name] = i
	}
	for i, f := range m.Functions {
		e.funcIndex[f.Name] = i
	}
	e.line("// Generated by Tach. Portable WGSL compute profile.")
	if ir.UsesKind(m, foundation.Float16Kind) {
		e.line("enable f16;")
	}
	e.line("")
	for _, t := range m.Structs {
		e.emitStruct(t)
		e.line("")
	}
	for kernelIndex, kernel := range executable.PhysicalKernels {
		for bufferIndex, buffer := range kernel.Function.BufferParams {
			if kernel.Bindings[bufferIndex].Texture {
				e.line("@group(0) @binding(%d) var %s: texture_storage_2d<rgba8unorm, write>;", bufferIndex, resourceName(kernelIndex, bufferIndex))
			} else {
				e.emitResource(kernelIndex, bufferIndex, buffer)
			}
			e.line("")
		}
		if kernel.Parameters != nil {
			e.emitParameterBlock(kernel.Parameters)
			e.line("")
		}
	}
	for _, f := range m.Functions {
		if f.Kind == ir.Helper {
			continue
		}
		for i, w := range f.WorkgroupVars {
			e.line("var<workgroup> %s: %s;", workgroupName(f, i), e.typeName(w.Type))
		}
		if len(f.WorkgroupVars) > 0 {
			e.line("")
		}
	}
	for _, f := range m.Functions {
		if f.Kind == ir.Helper {
			if err := e.emitFunction(f); err != nil {
				return "", err
			}
			e.line("")
		}
	}
	for _, f := range m.Functions {
		if f.Kind == ir.Stage {
			if err := e.emitFunction(f); err != nil {
				return "", err
			}
			e.line("")
		}
	}
	out := e.b.String()
	if err := Validate(out); err != nil {
		return "", fmt.Errorf("tach WGSL self-validation failed: %w", err)
	}
	return out, nil
}

func viewTexture(physical *backend.PhysicalKernel, buffer int) bool {
	return physical != nil && buffer >= 0 && buffer < len(physical.Bindings) && physical.Bindings[buffer].Texture
}

func (e *emitter) line(s string, args ...any) {
	for i := 0; i < e.indent; i++ {
		e.b.WriteString("  ")
	}
	if len(args) > 0 {
		fmt.Fprintf(&e.b, s, args...)
	} else {
		e.b.WriteString(s)
	}
	e.b.WriteByte('\n')
}
func (e *emitter) typeName(t *foundation.Type) string {
	switch t.Kind {
	case foundation.VoidKind:
		return "void"
	case foundation.BoolKind:
		return "bool"
	case foundation.Int32Kind:
		return "i32"
	case foundation.Uint32Kind:
		return "u32"
	case foundation.Float16Kind:
		return "f16"
	case foundation.Float32Kind:
		return "f32"
	case foundation.VectorKind:
		return fmt.Sprintf("vec%d<%s>", t.Lanes, e.typeName(t.Elem))
	case foundation.StructKind:
		return mangleType(t.Name)
	case foundation.AtomicKind:
		return fmt.Sprintf("atomic<%s>", e.typeName(t.Elem))
	case foundation.FixedArrayKind:
		return fmt.Sprintf("array<%s, %d>", e.typeName(t.Elem), t.Count)
	case foundation.RuntimeArrayKind:
		return fmt.Sprintf("array<%s>", e.typeName(t.Elem))
	default:
		return "__invalid"
	}
}
func (e *emitter) emitStruct(t *foundation.Type) {
	e.line("// Tach type: %s", t.Name)
	e.line("struct %s {", mangleType(t.Name))
	e.indent++
	for i, f := range t.Fields {
		prefix := ""
		if i == 0 && !hasRuntimeTail(t) {
			prefix = "@align(16) "
		}
		e.line("%s%s: %s,", prefix, fieldName(i, f.Name), e.typeName(f.Type))
	}
	e.indent--
	e.line("}")
}
func (e *emitter) emitResource(kernel, buffer int, r ir.BufferParam) {
	e.line("// Tach resource: %s", r.Name)
	access := "read"
	if r.Access == ir.Mutable || foundation.ContainsAtomic(r.Type) {
		access = "read_write"
	}
	if r.Type.Kind == foundation.StructKind && hasRuntimeTail(r.Type) {
		e.line("@group(0) @binding(%d) var<storage, %s> %s: %s;", buffer, access, resourceName(kernel, buffer), e.typeName(r.Type))
		return
	}
	w := wrapperName(kernel, buffer)
	e.line("struct %s {", w)
	e.indent++
	fieldType := e.typeName(r.Type)
	if hasRuntimeTail(r.Type) {
		// Runtime array length is derived from the bound byte size. Imposing the
		// fixed-resource 16-byte wrapper alignment here would raise the shader's
		// minimum binding size and turn padding bytes into phantom elements.
		e.line("data: %s,", fieldType)
	} else {
		e.line("@align(16) data: %s,", fieldType)
	}
	e.indent--
	e.line("}")
	e.line("@group(0) @binding(%d) var<storage, %s> %s: %s;", buffer, access, resourceName(kernel, buffer), w)
}

func parameterTypeName(block *ir.HostParameterBlock) string {
	return "_tach_parameters_" + ir.MangleIdentifier(block.Function.Name)
}

func parameterResourceName(block *ir.HostParameterBlock) string {
	return "_tach_p_" + ir.MangleIdentifier(block.Function.Name)
}

func (e *emitter) emitParameterBlock(block *ir.HostParameterBlock) {
	e.line("// Tach parameters: %s", block.Function.Name)
	e.line("struct %s {", parameterTypeName(block))
	e.indent++
	for index, field := range block.Fields {
		prefix := ""
		if index == 0 {
			prefix = "@align(16) "
		}
		e.line("%s%s: %s,", prefix, field.Name, e.typeName(field.Physical))
	}
	e.indent--
	e.line("}")
	e.line("@group(0) @binding(%d) var<uniform> %s: %s;", block.Binding, parameterResourceName(block), parameterTypeName(block))
}

func hasRuntimeTail(t *foundation.Type) bool {
	if t == nil {
		return false
	}
	if t.Kind == foundation.RuntimeArrayKind {
		return true
	}
	return t.Kind == foundation.StructKind && len(t.Fields) > 0 && hasRuntimeTail(t.Fields[len(t.Fields)-1].Type)
}

func (e *emitter) funcName(f *ir.Function) string {
	if f.Kind == ir.Stage {
		return f.Name
	}
	return mangleFunc(f.Name)
}
func (e *emitter) emitFunction(f *ir.Function) error {
	if f.Kind == ir.Stage {
		e.line("// Tach compute entry: %s", f.Name)
		workgroup := e.p.kernels[f].Workgroup
		e.line("@compute @workgroup_size(%d, %d, %d)", workgroup[0], workgroup[1], workgroup[2])
	}
	var params []string
	if f.Kind == ir.Stage {
		lowered := e.p.functions[f]
		if needs(lowered, backend.Global) {
			params = append(params, "@builtin(global_invocation_id) _tach_global_index: vec3<u32>")
		}
		if needs(lowered, backend.Local) {
			params = append(params, "@builtin(local_invocation_id) _tach_local_index: vec3<u32>")
		}
		if needs(lowered, backend.LocalLinear) {
			params = append(params, "@builtin(local_invocation_index) _tach_local_linear: u32")
		}
	} else {
		for _, p := range f.Params {
			params = append(params, fmt.Sprintf("_v%d: %s", p.ID, e.typeName(p.Type)))
		}
	}
	head := fmt.Sprintf("fn %s(%s)", e.funcName(f), strings.Join(params, ", "))
	if f.Return.Kind != foundation.VoidKind {
		head += fmt.Sprintf(" -> %s", e.typeName(f.Return))
	}
	e.line("%s {", head)
	e.indent++
	st := &fnState{e: e, f: f, lowered: e.p.functions[f], values: map[ir.ValueID]*foundation.Type{}, places: map[ir.PlaceID]placeExpr{}}
	for _, id := range st.lowered.Order {
		if st.lowered.Uses[id] == 0 {
			continue
		}
		value, _ := expression(st.lowered, id)
		e.line("let %s: u32 = %s;", v(id), value)
		st.def(id, foundation.Uint32Type)
	}
	for _, p := range f.Params {
		if f.Kind == ir.Helper {
			st.values[p.ID] = p.Type
		}
	}
	if f.Kind == ir.Stage {
		block := e.p.kernels[f].Parameters
		cursor := 0
		for parameter, p := range f.Params {
			expression, err := e.parameterExpression(block, parameter, p.Type, &cursor)
			if err != nil {
				return err
			}
			e.line("let %s: %s = %s;", v(p.ID), e.typeName(p.Type), expression)
			st.def(p.ID, p.Type)
		}
		if block != nil && cursor != len(block.Fields) {
			return fmt.Errorf("kernel %s parameter block consumed %d of %d fields", f.Name, cursor, len(block.Fields))
		}
	}
	if err := st.emitBlock(f.Body, nil); err != nil {
		return err
	}
	e.indent--
	e.line("}")
	return nil
}

func (e *emitter) parameterExpression(block *ir.HostParameterBlock, parameter int, logical *foundation.Type, cursor *int) (string, error) {
	if logical.Kind == foundation.StructKind {
		values := make([]string, len(logical.Fields))
		for index, field := range logical.Fields {
			value, err := e.parameterExpression(block, parameter, field.Type, cursor)
			if err != nil {
				return "", err
			}
			values[index] = value
		}
		return fmt.Sprintf("%s(%s)", e.typeName(logical), strings.Join(values, ", ")), nil
	}
	if block == nil || *cursor >= len(block.Fields) {
		return "", fmt.Errorf("kernel parameter %d has no physical field", parameter)
	}
	field := block.Fields[*cursor]
	*cursor = *cursor + 1
	if field.Parameter != parameter || !foundation.Equal(field.Logical, logical) {
		return "", fmt.Errorf("kernel parameter %d field %d does not match %s", parameter, *cursor-1, logical)
	}
	expression := parameterResourceName(block) + "." + field.Name
	if logical.Kind == foundation.BoolKind {
		expression = "(" + expression + " != 0u)"
	}
	return expression, nil
}

type placeExpr struct {
	expr     string
	ty       *foundation.Type
	resource int
	index    string
}
type fnState struct {
	e       *emitter
	f       *ir.Function
	lowered *backend.Coordinates
	values  map[ir.ValueID]*foundation.Type
	places  map[ir.PlaceID]placeExpr
	loops   []*ir.Loop
}

func v(id ir.ValueID) string                             { return fmt.Sprintf("_v%d", id) }
func (s *fnState) def(id ir.ValueID, t *foundation.Type) { s.values[id] = t }
func (s *fnState) emitInstrs(b *ir.Block) error {
	for _, in := range b.Instrs {
		if err := s.emitInstr(in); err != nil {
			return err
		}
	}
	return nil
}

func (s *fnState) emitLoopTransfer(values []ir.ValueID, keyword string) error {
	if len(s.loops) == 0 {
		return fmt.Errorf("%s outside loop", keyword)
	}
	loop := s.loops[len(s.loops)-1]
	for i, id := range values {
		s.e.line("%s = %s;", v(loop.Results[i].ID), v(id))
	}
	s.e.line("%s;", keyword)
	return nil
}

func (s *fnState) emitBlock(b *ir.Block, yieldTargets []ir.Result) error {
	if err := s.emitInstrs(b); err != nil {
		return err
	}
	switch t := b.Term.(type) {
	case *ir.Return:
		if t.HasValue {
			s.e.line("return %s;", v(t.Value))
		} else {
			s.e.line("return;")
		}
	case *ir.Yield:
		for i, id := range t.Values {
			if i < len(yieldTargets) {
				s.e.line("%s = %s;", v(yieldTargets[i].ID), v(id))
			}
		}
	case *ir.Continue:
		return s.emitLoopTransfer(t.Values, "continue")
	case *ir.Break:
		return s.emitLoopTransfer(t.Values, "break")
	case *ir.Unreachable:
	case *ir.ExitScope:
		s.e.line("break;")
	default:
		return fmt.Errorf("unknown WGSL block terminator %T", b.Term)
	}
	return nil
}
func (s *fnState) emitInstr(in ir.Instr) error {
	e := s.e
	if definition, ok := in.(ir.ValueDef); ok && s.lowered != nil && s.lowered.Replaced[definition.ResultValue()] {
		return nil
	}
	switch x := in.(type) {
	case *ir.Const:
		if s.lowered != nil && s.lowered.Uses[x.Result] == 0 {
			return nil
		}
		raw := x.Raw
		if x.Type.Kind == foundation.Uint32Kind {
			raw += "u"
		}
		if x.Type.Kind == foundation.Int32Kind {
			raw += "i"
		}
		e.line("let %s: %s = %s;", v(x.Result), e.typeName(x.Type), raw)
		s.def(x.Result, x.Type)
	case *ir.Unary:
		e.line("let %s: %s = %s%s;", v(x.Result), e.typeName(x.Type), x.Op, v(x.X))
		s.def(x.Result, x.Type)
	case *ir.Binary:
		op := x.Op
		if op == "^" && foundation.IsBoolean(x.Type) {
			op = "!="
		}
		e.line("let %s: %s = %s %s %s;", v(x.Result), e.typeName(x.Type), v(x.Left), op, v(x.Right))
		s.def(x.Result, x.Type)
	case *ir.Intrinsic:
		args := make([]string, len(x.Args))
		for i, id := range x.Args {
			args[i] = v(id)
		}
		name := x.Kind.String()
		if x.Kind == ir.IntrinsicRSqrt {
			name = "inverseSqrt"
		}
		if x.Kind == ir.IntrinsicSelect {
			args = []string{args[2], args[1], args[0]}
		}
		switch x.Kind {
		case ir.IntrinsicMin:
			name, args = "select", []string{args[0], args[1], fmt.Sprintf("%s < %s", args[1], args[0])}
		case ir.IntrinsicMax:
			name, args = "select", []string{args[0], args[1], fmt.Sprintf("%s < %s", args[0], args[1])}
		case ir.IntrinsicClamp:
			bounded := v(x.Result) + "_bounded"
			e.line("let %s: %s = select(%s, %s, %s < %s);", bounded, e.typeName(x.Type), args[0], args[1], args[0], args[1])
			name, args = "select", []string{bounded, args[2], fmt.Sprintf("%s < %s", args[2], bounded)}
		}
		e.line("let %s: %s = %s(%s);", v(x.Result), e.typeName(x.Type), name, strings.Join(args, ", "))
		s.def(x.Result, x.Type)
	case *ir.Convert:
		e.line("let %s: %s = %s(%s);", v(x.Result), e.typeName(x.Type), e.typeName(x.Type), v(x.X))
		s.def(x.Result, x.Type)
	case *ir.Composite:
		args := make([]string, len(x.Values))
		for i, id := range x.Values {
			args[i] = v(id)
		}
		e.line("let %s: %s = %s(%s);", v(x.Result), e.typeName(x.Type), e.typeName(x.Type), strings.Join(args, ", "))
		s.def(x.Result, x.Type)
	case *ir.Extract:
		bt := s.values[x.Base]
		if bt == nil {
			return fmt.Errorf("WGSL extract base %%%d has no type", x.Base)
		}
		sel := ""
		if bt.Kind == foundation.StructKind {
			sel = fieldName(x.Index, bt.Fields[x.Index].Name)
		} else {
			sel = []string{"x", "y", "z", "w"}[x.Index]
		}
		e.line("let %s: %s = %s.%s;", v(x.Result), e.typeName(x.Type), v(x.Base), sel)
		s.def(x.Result, x.Type)
	case *ir.VectorIndex:
		e.line("let %s: %s = %s[%s];", v(x.Result), e.typeName(x.Type), v(x.Base), v(x.Index))
		s.def(x.Result, x.Type)
	case *ir.Call:
		args := make([]string, len(x.Args))
		for i, id := range x.Args {
			args[i] = v(id)
		}
		callee := s.e.m.Function(x.Function)
		if callee == nil {
			return fmt.Errorf("unknown callee %s", x.Function)
		}
		if x.Type.Kind == foundation.VoidKind {
			e.line("%s(%s);", s.e.funcName(callee), strings.Join(args, ", "))
		} else {
			e.line("let %s: %s = %s(%s);", v(x.Result), e.typeName(x.Type), s.e.funcName(callee), strings.Join(args, ", "))
			s.def(x.Result, x.Type)
		}
	case *ir.PlaceRoot:
		kernel := s.e.kernelIndex[s.f]
		name := resourceName(kernel, x.Buffer)
		if viewTexture(s.e.p.kernels[s.f], x.Buffer) {
			s.places[x.Result] = placeExpr{expr: name, ty: x.Type, resource: x.Buffer}
		} else if x.Type.Kind == foundation.StructKind && hasRuntimeTail(x.Type) {
			s.places[x.Result] = placeExpr{expr: name, ty: x.Type, resource: x.Buffer}
		} else {
			s.places[x.Result] = placeExpr{expr: name + ".data", ty: x.Type, resource: x.Buffer}
		}
	case *ir.PlaceWorkgroup:
		if x.Workgroup < 0 || x.Workgroup >= len(s.f.WorkgroupVars) {
			return fmt.Errorf("invalid workgroup place %d", x.Workgroup)
		}
		s.places[x.Result] = placeExpr{expr: workgroupName(s.f, x.Workgroup), ty: x.Type, resource: -1}
	case *ir.PlaceField:
		p := s.places[x.Base]
		if p.ty == nil {
			return fmt.Errorf("unknown place &p%d", x.Base)
		}
		name := fieldName(x.Field, p.ty.Fields[x.Field].Name)
		s.places[x.Result] = placeExpr{expr: p.expr + "." + name, ty: x.Type, resource: p.resource, index: p.index}
	case *ir.PlaceIndex:
		p := s.places[x.Base]
		if p.ty == nil {
			return fmt.Errorf("unknown place &p%d", x.Base)
		}
		s.places[x.Result] = placeExpr{expr: fmt.Sprintf("%s[%s]", p.expr, v(x.Index)), ty: x.Type, resource: p.resource, index: v(x.Index)}
	case *ir.Load:
		p := s.places[x.Place]
		if p.ty == nil {
			return fmt.Errorf("unknown load place &p%d", x.Place)
		}
		e.line("let %s: %s = %s;", v(x.Result), e.typeName(x.Type), p.expr)
		s.def(x.Result, x.Type)
	case *ir.Store:
		p := s.places[x.Place]
		if p.ty == nil {
			return fmt.Errorf("unknown store place &p%d", x.Place)
		}
		physical := s.e.p.kernels[s.f]
		if viewTexture(physical, p.resource) {
			if p.index == "" {
				return fmt.Errorf("view store has no pixel index")
			}
			xCoord, yCoord := p.index+" % "+v(physical.ViewWidth), p.index+" / "+v(physical.ViewWidth)
			if physical.Projection && len(s.f.Indices) >= 2 {
				xCoord, yCoord = v(s.f.Indices[0].ID), v(s.f.Indices[1].ID)
			}
			e.line("textureStore(%s, vec2<u32>(%s, %s), unpack4x8unorm(%s));", resourceName(s.e.kernelIndex[s.f], p.resource), xCoord, yCoord, v(x.Value))
		} else {
			e.line("%s = %s;", p.expr, v(x.Value))
		}
	case *ir.Atomic:
		p := s.places[x.Place]
		if p.ty == nil {
			return fmt.Errorf("unknown atomic place &p%d", x.Place)
		}
		name := ""
		switch x.Op {
		case ir.AtomicLoad:
			name = "atomicLoad"
		case ir.AtomicStore:
			name = "atomicStore"
		case ir.AtomicAdd:
			name = "atomicAdd"
		case ir.AtomicSub:
			name = "atomicSub"
		case ir.AtomicMin:
			name = "atomicMin"
		case ir.AtomicMax:
			name = "atomicMax"
		case ir.AtomicAnd:
			name = "atomicAnd"
		case ir.AtomicOr:
			name = "atomicOr"
		case ir.AtomicXor:
			name = "atomicXor"
		case ir.AtomicExchange:
			name = "atomicExchange"
		case ir.AtomicCompareExchange:
			name = "atomicCompareExchangeWeak"
		default:
			return fmt.Errorf("unknown atomic op %d", x.Op)
		}
		if x.Op == ir.AtomicCompareExchange {
			attempt := v(x.Result) + "_attempt"
			e.line("var %s: %s;", v(x.Result), e.typeName(x.Type))
			e.line("loop {")
			e.indent++
			e.line("let %s = %s(&%s, %s, %s);", attempt, name, p.expr, v(x.Expected), v(x.Value))
			e.line("%s = %s.old_value;", v(x.Result), attempt)
			e.line("if (%s.exchanged || %s.old_value != %s) { break; }", attempt, attempt, v(x.Expected))
			e.indent--
			e.line("}")
			s.def(x.Result, x.Type)
		} else if x.Op == ir.AtomicStore {
			e.line("%s(&%s, %s);", name, p.expr, v(x.Value))
		} else if x.Op == ir.AtomicLoad {
			e.line("let %s: %s = %s(&%s);", v(x.Result), e.typeName(x.Type), name, p.expr)
			s.def(x.Result, x.Type)
		} else {
			e.line("let %s: %s = %s(&%s, %s);", v(x.Result), e.typeName(x.Type), name, p.expr, v(x.Value))
			s.def(x.Result, x.Type)
		}
	case *ir.Barrier:
		switch x.Kind {
		case ir.BarrierWorkgroup:
			e.line("workgroupBarrier();")
		case ir.BarrierBuffer:
			e.line("storageBarrier();")
		default:
			return fmt.Errorf("unknown barrier kind %d", x.Kind)
		}
	case *ir.ArrayLength:
		p := s.places[x.Place]
		if p.ty == nil {
			return fmt.Errorf("unknown array length place &p%d", x.Place)
		}
		physical := s.e.p.kernels[s.f]
		if viewTexture(physical, p.resource) {
			e.line("let %s: u32 = %s * %s;", v(x.Result), v(physical.ViewWidth), v(physical.ViewHeight))
		} else if length, ok := physical.LogicalLengths[p.resource]; ok {
			e.line("let %s: u32 = %s;", v(x.Result), v(length))
		} else {
			e.line("let %s: u32 = arrayLength(&%s);", v(x.Result), p.expr)
		}
		s.def(x.Result, foundation.Uint32Type)
	case *ir.If:
		for _, r := range x.Results {
			e.line("var %s: %s;", v(r.ID), e.typeName(r.Type))
			s.def(r.ID, r.Type)
		}
		e.line("if (%s) {", v(x.Cond))
		e.indent++
		if err := s.emitBlock(x.Then, x.Results); err != nil {
			return err
		}
		e.indent--
		e.line("} else {")
		e.indent++
		if err := s.emitBlock(x.Else, x.Results); err != nil {
			return err
		}
		e.indent--
		e.line("}")
	case *ir.Loop:
		for i, r := range x.Results {
			e.line("var %s: %s = %s;", v(r.ID), e.typeName(r.Type), v(x.Params[i].Init))
			s.def(r.ID, r.Type)
			s.def(x.Params[i].ID, x.Params[i].Type)
		}
		e.line("loop {")
		e.indent++
		s.loops = append(s.loops, x)
		for i, p := range x.Params {
			e.line("let %s: %s = %s;", v(p.ID), e.typeName(p.Type), v(x.Results[i].ID))
		}
		if err := s.emitInstrs(x.Cond); err != nil {
			return err
		}
		cy, ok := x.Cond.Term.(*ir.Yield)
		if !ok || len(cy.Values) != 1 {
			return fmt.Errorf("loop condition malformed")
		}
		e.line("if (!%s) { break; }", v(cy.Values[0]))
		err := s.emitBlock(x.Body, nil)
		s.loops = s.loops[:len(s.loops)-1]
		if err != nil {
			return err
		}
		e.indent--
		e.line("}")
	case *ir.Scope:
		e.line("loop {")
		e.indent++
		if err := s.emitBlock(x.Body, nil); err != nil {
			return err
		}
		if _, exits := x.Body.Term.(*ir.ExitScope); !exits {
			if _, returns := x.Body.Term.(*ir.Return); !returns {
				e.line("break;")
			}
		}
		e.indent--
		e.line("}")
	default:
		return fmt.Errorf("unknown WGSL instruction %T", in)
	}
	return nil
}
