package wgsl

import (
	"fmt"
	"strings"

	"tach/src/abi"
	"tach/src/backend"
	"tach/src/ir"
	"tach/src/types"
)

func mangleFunc(name string) string          { return "_tach_f_" + abi.Mangle(name) }
func mangleType(name string) string          { return "_tach_t_" + abi.Mangle(name) }
func resourceName(kernel, buffer int) string { return fmt.Sprintf("_tach_r%d_%d", kernel, buffer) }
func wrapperName(kernel, buffer int) string {
	return fmt.Sprintf("_tach_resource_%d_%d", kernel, buffer)
}
func fieldName(i int, name string) string { return fmt.Sprintf("f%d_%s", i, abi.Mangle(name)) }
func workgroupName(f *ir.Function, i int) string {
	return fmt.Sprintf("_tach_w_%s_%d", abi.Mangle(f.Name), i)
}

type emitter struct {
	p           *program
	m           *ir.Module
	b           strings.Builder
	indent      int
	structIndex map[string]int
	funcIndex   map[string]int
	kernelIndex map[*ir.Function]int
}

func Emit(executable *backend.Executable) (string, error) {
	if err := backend.Verify(executable); err != nil {
		return "", err
	}
	p, err := lower(executable)
	if err != nil {
		return "", err
	}
	m := executable.KernelModule
	e := &emitter{p: p, m: m, structIndex: map[string]int{}, funcIndex: map[string]int{}, kernelIndex: map[*ir.Function]int{}}
	for i := range executable.PhysicalKernels {
		e.kernelIndex[executable.PhysicalKernels[i].Function] = i
	}
	for i, t := range m.Structs {
		e.structIndex[t.Name] = i
	}
	for i, f := range m.Functions {
		e.funcIndex[f.Name] = i
	}
	e.line("// Generated by Tach. Portable WGSL compute profile.")
	e.line("")
	for _, t := range m.Structs {
		e.emitStruct(t)
		e.line("")
	}
	for kernelIndex, kernel := range executable.PhysicalKernels {
		for bufferIndex, buffer := range kernel.Function.BufferParams {
			e.emitResource(kernelIndex, bufferIndex, buffer)
			e.line("")
		}
		if kernel.Parameters != nil {
			e.emitParameterBlock(kernel.Parameters)
			e.line("")
		}
	}
	for _, f := range m.Functions {
		if f.Kind == ir.Helper {
			continue
		}
		for i, w := range f.WorkgroupVars {
			e.line("var<workgroup> %s: %s;", workgroupName(f, i), e.typeName(w.Type))
		}
		if len(f.WorkgroupVars) > 0 {
			e.line("")
		}
	}
	for _, f := range m.Functions {
		if f.Kind == ir.Helper {
			if err := e.emitFunction(f); err != nil {
				return "", err
			}
			e.line("")
		}
	}
	for _, f := range m.Functions {
		if f.Kind == ir.Stage {
			if err := e.emitFunction(f); err != nil {
				return "", err
			}
			e.line("")
		}
	}
	out := e.b.String()
	if err := Validate(out); err != nil {
		return "", fmt.Errorf("Tach WGSL self-validation failed: %w", err)
	}
	return out, nil
}

func (e *emitter) line(s string, args ...any) {
	for i := 0; i < e.indent; i++ {
		e.b.WriteString("  ")
	}
	if len(args) > 0 {
		fmt.Fprintf(&e.b, s, args...)
	} else {
		e.b.WriteString(s)
	}
	e.b.WriteByte('\n')
}
func (e *emitter) typeName(t *types.Type) string {
	switch t.Kind {
	case types.Void:
		return "void"
	case types.Bool:
		return "bool"
	case types.I32:
		return "i32"
	case types.U32:
		return "u32"
	case types.F32:
		return "f32"
	case types.Vector:
		return fmt.Sprintf("vec%d<%s>", t.Lanes, e.typeName(t.Elem))
	case types.Struct:
		return mangleType(t.Name)
	case types.Atomic:
		return fmt.Sprintf("atomic<%s>", e.typeName(t.Elem))
	case types.FixedArray:
		return fmt.Sprintf("array<%s, %d>", e.typeName(t.Elem), t.Count)
	case types.RuntimeArray:
		return fmt.Sprintf("array<%s>", e.typeName(t.Elem))
	default:
		return "__invalid"
	}
}
func (e *emitter) emitStruct(t *types.Type) {
	e.line("// Tach type: %s", t.Name)
	e.line("struct %s {", mangleType(t.Name))
	e.indent++
	for i, f := range t.Fields {
		prefix := ""
		if i == 0 {
			prefix = "@align(16) "
		}
		e.line("%s%s: %s,", prefix, fieldName(i, f.Name), e.typeName(f.Type))
	}
	e.indent--
	e.line("}")
}
func (e *emitter) emitResource(kernel, buffer int, r ir.BufferParam) {
	w := wrapperName(kernel, buffer)
	e.line("// Tach resource: %s", r.Name)
	e.line("struct %s {", w)
	e.indent++
	fieldType := e.typeName(r.Type)
	if hasRuntimeTail(r.Type) {
		// Runtime array length is derived from the bound byte size. Imposing the
		// fixed-resource 16-byte wrapper alignment here would raise the shader's
		// minimum binding size and turn padding bytes into phantom elements.
		e.line("data: %s,", fieldType)
	} else {
		e.line("@align(16) data: %s,", fieldType)
	}
	e.indent--
	e.line("}")
	access := "read"
	if r.Access == ir.Mutable || types.ContainsAtomic(r.Type) {
		access = "read_write"
	}
	e.line("@group(0) @binding(%d) var<storage, %s> %s: %s;", buffer, access, resourceName(kernel, buffer), w)
}

func parameterTypeName(block *abi.ParameterBlock) string {
	return "_tach_parameters_" + abi.Mangle(block.Function.Name)
}

func parameterResourceName(block *abi.ParameterBlock) string {
	return "_tach_p_" + abi.Mangle(block.Function.Name)
}

func (e *emitter) emitParameterBlock(block *abi.ParameterBlock) {
	e.line("// Tach parameters: %s", block.Function.Name)
	e.line("struct %s {", parameterTypeName(block))
	e.indent++
	for index, field := range block.Fields {
		prefix := ""
		if index == 0 {
			prefix = "@align(16) "
		}
		e.line("%s%s: %s,", prefix, field.Name, e.typeName(field.Physical))
	}
	e.indent--
	e.line("}")
	e.line("@group(0) @binding(%d) var<uniform> %s: %s;", block.Binding, parameterResourceName(block), parameterTypeName(block))
}

func hasRuntimeTail(t *types.Type) bool {
	if t == nil {
		return false
	}
	if t.Kind == types.RuntimeArray {
		return true
	}
	return t.Kind == types.Struct && len(t.Fields) > 0 && hasRuntimeTail(t.Fields[len(t.Fields)-1].Type)
}

func (e *emitter) funcName(f *ir.Function) string {
	if f.Kind == ir.Stage {
		return f.Name
	}
	return mangleFunc(f.Name)
}
func (e *emitter) emitFunction(f *ir.Function) error {
	if f.Kind == ir.Stage {
		e.line("// Tach compute entry: %s", f.Name)
		workgroup := e.p.kernels[f].Workgroup
		e.line("@compute @workgroup_size(%d, %d, %d)", workgroup[0], workgroup[1], workgroup[2])
	}
	var params []string
	if f.Kind == ir.Stage {
		lowered := e.p.functions[f]
		if lowered.needsGlobal() {
			params = append(params, "@builtin(global_invocation_id) _tach_global_index: vec3<u32>")
		}
		if lowered.needsLocal() {
			params = append(params, "@builtin(local_invocation_id) _tach_local_index: vec3<u32>")
		}
		if lowered.needsLocalLinear() {
			params = append(params, "@builtin(local_invocation_index) _tach_local_linear: u32")
		}
	} else {
		for _, p := range f.Params {
			params = append(params, fmt.Sprintf("_v%d: %s", p.ID, e.typeName(p.Type)))
		}
	}
	head := fmt.Sprintf("fn %s(%s)", e.funcName(f), strings.Join(params, ", "))
	if f.Return.Kind != types.Void {
		head += fmt.Sprintf(" -> %s", e.typeName(f.Return))
	}
	e.line(head + " {")
	e.indent++
	st := &fnState{e: e, f: f, lowered: e.p.functions[f], values: map[ir.ValueID]*types.Type{}, places: map[ir.PlaceID]placeExpr{}}
	for _, id := range st.lowered.coordinates.Order {
		if st.lowered.uses(id) == 0 {
			continue
		}
		expression, _ := st.lowered.expression(id)
		e.line("let %s: u32 = %s;", v(id), expression)
		st.def(id, types.TU32)
	}
	for _, p := range f.Params {
		if f.Kind == ir.Helper {
			st.values[p.ID] = p.Type
		}
	}
	if f.Kind == ir.Stage {
		block := e.p.kernels[f].Parameters
		cursor := 0
		for parameter, p := range f.Params {
			expression, err := e.parameterExpression(block, parameter, p.Type, &cursor)
			if err != nil {
				return err
			}
			e.line("let %s: %s = %s;", v(p.ID), e.typeName(p.Type), expression)
			st.def(p.ID, p.Type)
		}
		if block != nil && cursor != len(block.Fields) {
			return fmt.Errorf("kernel %s parameter block consumed %d of %d fields", f.Name, cursor, len(block.Fields))
		}
	}
	if err := st.emitBlock(f.Body, nil, nil); err != nil {
		return err
	}
	e.indent--
	e.line("}")
	return nil
}

func (e *emitter) parameterExpression(block *abi.ParameterBlock, parameter int, logical *types.Type, cursor *int) (string, error) {
	if logical.Kind == types.Struct {
		values := make([]string, len(logical.Fields))
		for index, field := range logical.Fields {
			value, err := e.parameterExpression(block, parameter, field.Type, cursor)
			if err != nil {
				return "", err
			}
			values[index] = value
		}
		return fmt.Sprintf("%s(%s)", e.typeName(logical), strings.Join(values, ", ")), nil
	}
	if block == nil || *cursor >= len(block.Fields) {
		return "", fmt.Errorf("kernel parameter %d has no physical field", parameter)
	}
	field := block.Fields[*cursor]
	*cursor = *cursor + 1
	if field.Parameter != parameter || !types.Equal(field.Logical, logical) {
		return "", fmt.Errorf("kernel parameter %d field %d does not match %s", parameter, *cursor-1, logical)
	}
	expression := parameterResourceName(block) + "." + field.Name
	if logical.Kind == types.Bool {
		expression = "(" + expression + " != 0u)"
	}
	return expression, nil
}

type placeExpr struct {
	expr     string
	ty       *types.Type
	resource int
}
type fnState struct {
	e       *emitter
	f       *ir.Function
	lowered *loweredFunction
	values  map[ir.ValueID]*types.Type
	places  map[ir.PlaceID]placeExpr
}

func v(id ir.ValueID) string                        { return fmt.Sprintf("_v%d", id) }
func (s *fnState) def(id ir.ValueID, t *types.Type) { s.values[id] = t }
func (s *fnState) emitInstrs(b *ir.Block) error {
	for _, in := range b.Instrs {
		if err := s.emitInstr(in); err != nil {
			return err
		}
	}
	return nil
}
func (s *fnState) emitBlock(b *ir.Block, yieldTargets []ir.Result, loop *ir.Loop) error {
	if err := s.emitInstrs(b); err != nil {
		return err
	}
	switch t := b.Term.(type) {
	case *ir.Return:
		if t.HasValue {
			s.e.line("return %s;", v(t.Value))
		} else {
			s.e.line("return;")
		}
	case *ir.Yield:
		for i, id := range t.Values {
			if i < len(yieldTargets) {
				s.e.line("%s = %s;", v(yieldTargets[i].ID), v(id))
			}
		}
	case *ir.Continue:
		if loop == nil {
			return fmt.Errorf("continue outside loop")
		}
		for i, id := range t.Values {
			s.e.line("%s = %s;", v(loop.Results[i].ID), v(id))
		}
		s.e.line("continue;")
	case *ir.Unreachable:
	case *ir.ExitScope:
		s.e.line("break;")
	default:
		return fmt.Errorf("unknown WGSL block terminator %T", b.Term)
	}
	return nil
}
func (s *fnState) emitInstr(in ir.Instr) error {
	e := s.e
	if definition, ok := in.(ir.ValueDef); ok && s.lowered != nil && s.lowered.replaced(definition.ResultValue()) {
		return nil
	}
	switch x := in.(type) {
	case *ir.Const:
		if s.lowered != nil && s.lowered.uses(x.Result) == 0 {
			return nil
		}
		raw := x.Raw
		if x.Type.Kind == types.U32 {
			raw += "u"
		}
		if x.Type.Kind == types.I32 {
			raw += "i"
		}
		e.line("let %s: %s = %s;", v(x.Result), e.typeName(x.Type), raw)
		s.def(x.Result, x.Type)
	case *ir.Unary:
		e.line("let %s: %s = %s%s;", v(x.Result), e.typeName(x.Type), x.Op, v(x.X))
		s.def(x.Result, x.Type)
	case *ir.Binary:
		e.line("let %s: %s = %s %s %s;", v(x.Result), e.typeName(x.Type), v(x.Left), x.Op, v(x.Right))
		s.def(x.Result, x.Type)
	case *ir.Intrinsic:
		args := make([]string, len(x.Args))
		for i, id := range x.Args {
			args[i] = v(id)
		}
		name := x.Kind.String()
		if x.Kind == ir.IntrinsicRSqrt {
			name = "inverseSqrt"
		}
		e.line("let %s: %s = %s(%s);", v(x.Result), e.typeName(x.Type), name, strings.Join(args, ", "))
		s.def(x.Result, x.Type)
	case *ir.Convert:
		e.line("let %s: %s = %s(%s);", v(x.Result), e.typeName(x.Type), e.typeName(x.Type), v(x.X))
		s.def(x.Result, x.Type)
	case *ir.Composite:
		args := make([]string, len(x.Values))
		for i, id := range x.Values {
			args[i] = v(id)
		}
		e.line("let %s: %s = %s(%s);", v(x.Result), e.typeName(x.Type), e.typeName(x.Type), strings.Join(args, ", "))
		s.def(x.Result, x.Type)
	case *ir.Extract:
		bt := s.values[x.Base]
		if bt == nil {
			return fmt.Errorf("WGSL extract base %%%d has no type", x.Base)
		}
		sel := ""
		if bt.Kind == types.Struct {
			sel = fieldName(x.Index, bt.Fields[x.Index].Name)
		} else {
			sel = []string{"x", "y", "z", "w"}[x.Index]
		}
		e.line("let %s: %s = %s.%s;", v(x.Result), e.typeName(x.Type), v(x.Base), sel)
		s.def(x.Result, x.Type)
	case *ir.VectorIndex:
		e.line("let %s: %s = %s[%s];", v(x.Result), e.typeName(x.Type), v(x.Base), v(x.Index))
		s.def(x.Result, x.Type)
	case *ir.Call:
		args := make([]string, len(x.Args))
		for i, id := range x.Args {
			args[i] = v(id)
		}
		callee := s.e.m.Function(x.Function)
		if callee == nil {
			return fmt.Errorf("unknown callee %s", x.Function)
		}
		if x.Type.Kind == types.Void {
			e.line("%s(%s);", s.e.funcName(callee), strings.Join(args, ", "))
		} else {
			e.line("let %s: %s = %s(%s);", v(x.Result), e.typeName(x.Type), s.e.funcName(callee), strings.Join(args, ", "))
			s.def(x.Result, x.Type)
		}
	case *ir.PlaceRoot:
		kernel := s.e.kernelIndex[s.f]
		s.places[x.Result] = placeExpr{expr: resourceName(kernel, x.Buffer) + ".data", ty: x.Type, resource: x.Buffer}
	case *ir.PlaceWorkgroup:
		if x.Workgroup < 0 || x.Workgroup >= len(s.f.WorkgroupVars) {
			return fmt.Errorf("invalid workgroup place %d", x.Workgroup)
		}
		s.places[x.Result] = placeExpr{expr: workgroupName(s.f, x.Workgroup), ty: x.Type, resource: -1}
	case *ir.PlaceField:
		p := s.places[x.Base]
		if p.ty == nil {
			return fmt.Errorf("unknown place &p%d", x.Base)
		}
		name := fieldName(x.Field, p.ty.Fields[x.Field].Name)
		s.places[x.Result] = placeExpr{expr: p.expr + "." + name, ty: x.Type, resource: p.resource}
	case *ir.PlaceIndex:
		p := s.places[x.Base]
		if p.ty == nil {
			return fmt.Errorf("unknown place &p%d", x.Base)
		}
		s.places[x.Result] = placeExpr{expr: fmt.Sprintf("%s[%s]", p.expr, v(x.Index)), ty: x.Type, resource: p.resource}
	case *ir.Load:
		p := s.places[x.Place]
		if p.ty == nil {
			return fmt.Errorf("unknown load place &p%d", x.Place)
		}
		e.line("let %s: %s = %s;", v(x.Result), e.typeName(x.Type), p.expr)
		s.def(x.Result, x.Type)
	case *ir.Store:
		p := s.places[x.Place]
		if p.ty == nil {
			return fmt.Errorf("unknown store place &p%d", x.Place)
		}
		e.line("%s = %s;", p.expr, v(x.Value))
	case *ir.Atomic:
		p := s.places[x.Place]
		if p.ty == nil {
			return fmt.Errorf("unknown atomic place &p%d", x.Place)
		}
		name := ""
		switch x.Op {
		case ir.AtomicLoad:
			name = "atomicLoad"
		case ir.AtomicStore:
			name = "atomicStore"
		case ir.AtomicAdd:
			name = "atomicAdd"
		case ir.AtomicSub:
			name = "atomicSub"
		case ir.AtomicMin:
			name = "atomicMin"
		case ir.AtomicMax:
			name = "atomicMax"
		case ir.AtomicAnd:
			name = "atomicAnd"
		case ir.AtomicOr:
			name = "atomicOr"
		case ir.AtomicXor:
			name = "atomicXor"
		case ir.AtomicExchange:
			name = "atomicExchange"
		default:
			return fmt.Errorf("unknown atomic op %d", x.Op)
		}
		if x.Op == ir.AtomicStore {
			e.line("%s(&%s, %s);", name, p.expr, v(x.Value))
		} else if x.Op == ir.AtomicLoad {
			e.line("let %s: %s = %s(&%s);", v(x.Result), e.typeName(x.Type), name, p.expr)
			s.def(x.Result, x.Type)
		} else {
			e.line("let %s: %s = %s(&%s, %s);", v(x.Result), e.typeName(x.Type), name, p.expr, v(x.Value))
			s.def(x.Result, x.Type)
		}
	case *ir.Barrier:
		switch x.Kind {
		case ir.BarrierWorkgroup:
			e.line("workgroupBarrier();")
		case ir.BarrierBuffer:
			e.line("storageBarrier();")
		default:
			return fmt.Errorf("unknown barrier kind %d", x.Kind)
		}
	case *ir.ArrayLength:
		p := s.places[x.Place]
		if p.ty == nil {
			return fmt.Errorf("unknown array length place &p%d", x.Place)
		}
		e.line("let %s: u32 = arrayLength(&%s);", v(x.Result), p.expr)
		s.def(x.Result, types.TU32)
	case *ir.If:
		for _, r := range x.Results {
			e.line("var %s: %s;", v(r.ID), e.typeName(r.Type))
			s.def(r.ID, r.Type)
		}
		e.line("if (%s) {", v(x.Cond))
		e.indent++
		if err := s.emitBlock(x.Then, x.Results, nil); err != nil {
			return err
		}
		e.indent--
		e.line("} else {")
		e.indent++
		if err := s.emitBlock(x.Else, x.Results, nil); err != nil {
			return err
		}
		e.indent--
		e.line("}")
	case *ir.Loop:
		for i, r := range x.Results {
			e.line("var %s: %s = %s;", v(r.ID), e.typeName(r.Type), v(x.Params[i].Init))
			s.def(r.ID, r.Type)
			s.def(x.Params[i].ID, x.Params[i].Type)
		}
		e.line("loop {")
		e.indent++
		for i, p := range x.Params {
			e.line("let %s: %s = %s;", v(p.ID), e.typeName(p.Type), v(x.Results[i].ID))
		}
		if err := s.emitInstrs(x.Cond); err != nil {
			return err
		}
		cy, ok := x.Cond.Term.(*ir.Yield)
		if !ok || len(cy.Values) != 1 {
			return fmt.Errorf("loop condition malformed")
		}
		e.line("if (!%s) { break; }", v(cy.Values[0]))
		if err := s.emitBlock(x.Body, nil, x); err != nil {
			return err
		}
		e.indent--
		e.line("}")
	case *ir.Scope:
		e.line("loop {")
		e.indent++
		if err := s.emitBlock(x.Body, nil, nil); err != nil {
			return err
		}
		if _, exits := x.Body.Term.(*ir.ExitScope); !exits {
			if _, returns := x.Body.Term.(*ir.Return); !returns {
				e.line("break;")
			}
		}
		e.indent--
		e.line("}")
	default:
		return fmt.Errorf("unknown WGSL instruction %T", in)
	}
	return nil
}
